### ISSUE TITLE
Use WebSocket API instead of REST API

### ISSUE THREAD

**Issue by thebhumilsoni** [buildkite/test-collector-android#7]
## 💬  Context

Currently, the test data are uploaded using the REST API. To be consistent with the [ruby collector](https://github.com/buildkite/test-collector-ruby), update its usage with the WebSocket API.

## 📝 Notes

- Update the test data uploader implementation to use WebSocket API.

## 🤝 Related

**Comment by preflightcookie** [comment]
Thanks for the suggestion, @thebhumilsoni ! Since this was raised, we've deprecated the WebSocket approach in the Ruby collector, meaning that the REST API approach used here follows the same pattern as all other collectors. Given this change, I'll close off this issue.
